---
title: "Counting and locating people in surveillance footage"
author: "John Rapp Farnes"
date: "6/18/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(xml2)
folders <- Sys.glob("./CAVIAR/*")
xml_files <- Sys.glob("./CAVIAR/**/**.xml")

ks <- c()
obs <- data.frame()

for (f in xml_files) {
  # f <- xml_files[1]
  doc <- read_xml(f)
  # obj_list <- xml_find_all(doc, "frame//objectlist")[1]
  for (obj_list in xml_find_all(doc, "frame//objectlist")) {
    boxes <- xml_find_all(obj_list, "object/box")
    ks <- c(ks, length(boxes))
    # obj_attrs <- xml_attrs(boxes)[[1]]
    for (obj_attrs in xml_attrs(boxes)) {
      # obs <- rbind(obs, x=as.numeric(obj_attrs$x))
      obs <- rbind(obs, list(
        x=as.numeric(obj_attrs["xc"]),
        y=as.numeric(obj_attrs["yc"]),
        w=as.numeric(obj_attrs["w"]),
        h=as.numeric(obj_attrs["h"])))
    }
  }
}

# library(ggplot2)
library(GGally)
hist(ks)

ggpairs(obs)

plot_image(background)
points(obs$x/w, 1-obs$y/h)
```

```{r}
summary(lm(w ~ y, data = obs))

h_cutoff <- 210
summary(lm(obs$h[which(obs$y <= h_cutoff)] ~ obs$y[which(obs$y <= h_cutoff)], data = obs))
summary(lm(obs$h[which(obs$y > h_cutoff)] ~ obs$y[which(obs$y > h_cutoff)], data = obs))

w_model <- function(y) {
  11.6 + 0.14*y
}
h_model <- function(y) {
  ifelse(y <= h_cutoff, 22.8 + 0.5 * y, 527.8 - 1.86 * y)
}
w_sd <- 7
h_sd <- 12

min_w <- 5
min_h <- 5
```

```{r}
library(jpeg)
# current_frame_nr <- 2000; current_k <- 6 # många personer spridda
# current_frame_nr <- 3000; current_k <- 8 # många personer klumpade
# current_frame_nr <- 5000 # 4 personer spridda
# current_frame_nr <- 4000 # många personer långt borta klumpade
# current_frame_nr <- 200 # många personer spridda
# current_frame_nr <- 2500 # en nära, nåra borta
# current_frame_nr <- 800 # en nära, nåra borta
# current_frame_nr <- 4500 # tre personer, två ihop, en ensam nära
# current_frame_nr <- 20; current_k <- 4 # två nära ihop, två borta ihop
# current_frame_nr <- 3100 # många ihop
# current_frame_nr <- 5600 # tre nära
# current_frame_nr <- 5950 # två nära en vid väggen
# current_frame_nr <- 5750; current_k <- 4#; current_k <- 5 # fem utspridda
current_frame_nr <- 5964-47+2; current_k <- 3 # två spridda, en vid väggen
current_frame <- readJPEG(image_files[current_frame_nr], native=FALSE)


plot_image(current_frame)
```

```{r}
plot_image(current_frame)

xs <- runif(50)
ys <- runif(50)

ws <- rnorm(50, mean = w_model(ys*h), sd = w_sd)/h
hs <- rnorm(50, mean = h_model(ys*h), sd = h_sd)/h

rect(xs - ws/2, 1-(ys - hs/2), xs + ws/2, 1-(ys + ys/2), col=rgb(1,0,0,0.1))

plot(obs$y, obs$w)
points(ys*h, ws*h, col="red")

plot(obs$y, obs$h)
points(ys*h, hs*h, col="red")
```

```{r}
threshold <- 0.2
sd_multiplier <- 800
# sd_multiplier <- 0

background <- readJPEG("./bg.jpg", native=FALSE)
# background_var <- readJPEG("./bg_var.jpg", native=FALSE)

background_subtraction <- function(img, background) {
  mask <- array(dim=c(h,w))
  for (x in 1:w) {
    for (y in 1:h) {
      # mask[y, x] <- ifelse(abs(mean(img[y, x, c(1,2,3)])-mean(background[y, x, c(1,2,3)])) < threshold, 0, 1)
      # mask[y, x] <- ifelse(abs(mean(img[y, x, c(1,2,3)]-background[y, x, c(1,2,3)])) < threshold, 0, 1)
      mask[y, x] <- ifelse(abs(mean(img[y, x, c(1,2,3)]) - mean(background[y, x, c(1,2,3)])) < max(sd_multiplier*background_var[y, x], threshold), 0, 1)
      # mask[y, x] <- ifelse(abs(mean(img[y, x, c(1,2,3)]) - mean(background[y, x, c(1,2,3)])) < max(sd_multiplier^2*background_var[y, x], threshold), 0, 1)
    }
  }
  return (mask)
}

foreground <- background_subtraction(current_frame, background)

plot_image(from_grayscale(foreground))
plot_image(current_frame)
plot_image(background)
```


```{r}
points <- data.frame()

for (x in 1:w) {
  for (y in 1:h) {
    if (foreground[y, x] == 1) {
      points <- rbind(points, list(x=x,y=y))
    }
  }
}

plot(points$x, h-points$y)

clusters <- kmeans(points, current_k)

points(clusters$centers[,1], h-clusters$centers[,2], col="green")

for (k in 1:current_k) {
  xc <- clusters$centers[k, 1]
  yc <- clusters$centers[k, 2]
  
  ws <- rnorm(50, mean = w_model(yc), sd = w_sd)
  hs <- rnorm(50, mean = h_model(yc), sd = h_sd)
  
  rect(
    xc-ws/2,
    h-(yc-hs/2),
    xc+ws/2,
    h-(yc+hs/2),
    col = rgb(1,0,1,0.01)
  )
}
```

```{r}
# points <- list()
# 
# for (k in 1:current_k) {
#   xc <- clusters$centers[k, 1]
#   yc <- clusters$centers[k, 2]
#   
#   ww <- rnorm(1, mean = w_model(yc), sd = w_sd)
#   hh <- rnorm(1, mean = h_model(yc), sd = h_sd)
#   
#   points[[k]] <- list(x=xc,y=yc,w=ww,h=hh)
# }
# 
# initial_state <- list(
#   k = current_k,
#   points = points
# )
# 
render_state <- function(state, foreground, title=NULL) {
  plot_image(from_grayscale(foreground), title)

  cols <- c(
    rgb(1,0,0,0.5),
    rgb(0,1,0,0.5),
    rgb(0,0,1,0.5),
    rgb(1,0,1,0.5),
    rgb(1,1,0,0.5)
  )

  i <- 1
  for (point in state$points) {
    col <- cols[i %% length(cols) + 1]
    i <- i + 1
    rect((point$x - point$w/2) / w, 1-(point$y - point$h/2) / h, (point$x + point$w/2)/w, 1-(point$y + point$h/2)/h, col = col)
  }
}
# 
# render_state(initial_state)

points_unif <- list()
k_unif <- sample(1:10, 1)

for (k in 1:k_unif) {
  xc <- runif(1, 0, w)
  yc <- runif(1, 0, h)

  ww <- rnorm(1, mean = w_model(yc), sd = w_sd)
  hh <- rnorm(1, mean = h_model(yc), sd = h_sd)

  points_unif[[k]] <- list(x=xc,y=yc,w=ww,h=hh)
  
  points_unif[[k]]$x <- clamp(xc, ww/2+1, w-ww/2)
  points_unif[[k]]$y <- clamp(yc, hh/2+1, h-hh/2)
}

initial_state_unif <- list(
  k = k_unif,
  points = points_unif
)

initial_state_unif$likelihood <- likelihood(initial_state_unif)

render_state(initial_state_unif)
```



```{r}
metropolis_hastings <- function(q_sample, q_ratio, pi_ratio, N, initial_state) {
  state <- initial_state
  
  states <- list(state)
  
  for (i in 1:N) {
    proposed <- q_sample(state)
    
    alpha <- q_ratio(state, proposed) * pi_ratio(proposed, state)
    if (alpha >= 1 || runif(1) <= alpha) {
      state <- proposed
    }
      
    states <- append(states, list(state))
  }
  
  return (states)
}
```

```{r}
library(rlist)

likelihood <- function(state) {
  state_mask <- array(0, dim=c(h, w))

  overlap <- 0
  for (i in 1:state$k) {
    point <- state$points[[i]]
    for (x in round(point$x - point$w/2):round(point$x + point$w/2)) {
      for (y in round(point$y - point$h/2):round(point$y + point$h/2)) {
        if (state_mask[y, x] == 0) {
          state_mask[y, x] = 1
        } else {
          overlap <- overlap + 1
        }
      }
    }
  }
  N10 <- sum(state_mask == 1 & foreground == 0)
  N01 <- sum(state_mask == 0 & foreground == 1)

  measures <- c(N10, N01, overlap)

  # weights <- c(0.0001, 0.0001, 0.00005)
  # weights <- c(0.0005, 0.01, 0.001, 1000)*10

  weights <- c(0.0005, 0.01, 0.001)*10
  
  Z <- min(measures %*% weights, 600)

  # print(c(measures, Z, exp(-Z), prior(state)))

  return (exp(-Z) * prior(state))
}

pi_ratio <- function(state_1, state_2) {
  # print(c(likelihood(state_1), likelihood(state_2)))
  # likelihood(state_1) /  likelihood(state_2)
  state_1$likelihood /  state_2$likelihood
}

# x_sd <- w*.03
# y_sd <- h*.03
x_sd <- w*.2
y_sd <- h*.2
# propose_update <- function(state) {
#   i <- sample(1:state$k, 1)
#   p <- state$points[[i]]
# 
#   state$points[[i]]$x <- rnorm(1, mean = p$x, sd=x_sd)
#   state$points[[i]]$y <- rnorm(1, mean = p$y, sd=y_sd)
#   
#   p <- state$points[[i]]
#   state$points[[i]]$w <- clamp(rnorm(1, mean = w_model(p$y), sd = w_sd), min_w, w)
#   state$points[[i]]$h <- clamp(rnorm(1, mean = h_model(p$y), sd = h_sd), min_h, h)
#   
#   p <- state$points[[i]]
#   state$points[[i]]$x <- clamp(p$x, p$w/2+1, w-p$w/2)
#   state$points[[i]]$y <- clamp(p$y, p$h/2+1, h-p$h/2)
#   
#   # p -> state$points[[i]]
#     
#   return (state)
# }

propose_update <- function(state) {
  i <- sample(1:state$k, 1)
  p <- state$points[[i]]

  p$x <- rnorm(1, mean = p$x, sd=x_sd)
  p$y <- rnorm(1, mean = p$y, sd=y_sd)
  
  p$w <- clamp(rnorm(1, mean = w_model(p$y), sd = w_sd), min_w, w)
  p$h <- clamp(rnorm(1, mean = h_model(p$y), sd = h_sd), min_h, h)
  
  p$x <- clamp(p$x, p$w/2+1, w-p$w/2)
  p$y <- clamp(p$y, p$h/2+1, h-p$h/2)
  
  state$points[[i]] <- p
    
  return (state)
}

propose_birth <- function(state) {
  state$k <- state$k + 1
  
  p <- list(
    x = runif(1, 0, w),
    y = runif(1, 0, h)
  )
  
  p$w <- clamp(rnorm(1, mean = w_model(p$y), sd = w_sd), min_w, w)
  p$h <- clamp(rnorm(1, mean = h_model(p$y), sd = h_sd), min_h, h)
  
  p$x <- clamp(p$x, p$w/2+1, w-p$w/2)
  p$y <- clamp(p$y, p$h/2+1, h-p$h/2)
  
  state$points[[state$k]] <- p

  return (state)
}

propose_death <- function(state) {
  i <- sample(1:state$k, 1)
  
  state$k <- state$k - 1
  
  state$points <- list.remove(state$points, i)
  
  state$removed <- i

  return (state)
}

points_dist <- function(a, b) {
  (a$x-b$x)^2 + (a$y-b$y)^2
}

propose_merge <- function(state) {
  dists <- array(Inf, dim=c(state$k, state$k))
  
  for (i in 1:(state$k - 1)) {
    for (j in (i + 1):state$k) {
      pi <- state$points[[i]]
      pj <- state$points[[j]]
      dists[i, j] <- points_dist(pi, pj)
    }
  }
  
  remove_i <- floor(which(dists == min(dists)) / state$k)
  
  state$k <- state$k - 1
  
  state$points <- list.remove(state$points, remove_i)
  
  state$removed <- remove_i

  return (state)
}

# TODO birth and death proposal probabilities according to poisson

propose <- function(state) {
  
  process <- runif(1)
  
  new_state <- NULL
  
  if (process < 0.1) {
    new_state <- propose_birth(state)
  } else if (process < 0.2 && state$k > 1) {
    new_state <- propose_death(state)
  } else if (process < 0.25 && state$k > 1) {
    new_state <- propose_merge(state)
  } else {
    new_state <- propose_update(state)
  }
  
  new_state$likelihood <- likelihood(new_state)
  
  return (new_state)
}

prior <- function(x) {
  prob <- 1
  for (p in x$points) {
    prob <- prob * dnorm(p$w, mean = w_model(p$y), sd = w_sd) * dnorm(p$h, mean = h_model(p$y), sd = h_sd)
  }
  prob
}

proposal_update_prob <- function(x) {
  prior(x)
}

proposal_prob_ratio <- function(x, y) {
  k_diff <- y$k - x$k
  
  if (k_diff > 1) {
    # Expanded
    1 / prior(y$points[y$k])
  } else if (k_diff < 1) {
    # Contracted
    prior(x$points[y$removed]) / 1
  } else {
    # Updated
    proposal_update_prob(x) / proposal_update_prob(y)
  }
}

states <- metropolis_hastings(
  propose,
  proposal_prob_ratio,
  pi_ratio,
  3000,
  # initial_state
  initial_state_unif
)


ls <- c()
ps <- c()
ks <- c()
for (s in states) {
  # ls <- c(ls, likelihood(s))
  ls <- c(ls, s$likelihood)
  ps <- c(ps, prior(s))
  ks <- c(ks, s$k)
}
# plot(ls, col="black", type="l", ylim=c(0,quantile(c(ls, ps), 0.8)))
plot(ls, col="black", type="l", main="Posterior along MCMC runs")
# lines(ps, col="red")
plot(ks, type="l", main="Number of people along MCMC runs")
hist(ks)

render_states <- function(states, indices, title) {
  for (s in states[indices]) {
    render_state(s, title)
  }
}

render_states(states, seq(1,4), "first")
render_states(states, length(states)-seq(1,5)-1, "last")
render_states(states, order(ls, decreasing = 1)[c(seq(1,20))], "best")
render_states(states, order(ls, decreasing = 1)[c(length(states)-seq(1,5)-1)], "worst")
render_states(states, sample(1:length(states), 20), "random")
```
PERCENTAGE OF ACCEPTED ALPHA


```{r}
for (kk in min(ks):max(ks)) {
  indices <- which(ks == kk)
  
  render_states(states, indices[seq(1,2)], paste("first,k=",kk,sep=""))
  render_states(states, indices[length(indices)-seq(1,2)-1], paste("last,k=",kk,sep=""))
  render_states(states, order(ls[indices], decreasing = 1)[c(seq(1,2))], paste("best,k=",kk,sep=""))
  render_states(states, order(ls[indices], decreasing = 1)[c(length(indices)-seq(1,2)-1)], paste("worst,k=",kk,sep=""))
  render_states(states, sample(indices, 2), paste("random,k=",kk,sep=""))
}
```



```{r}
locs <- data.frame()
# for (s in states) {
#   locs <- rbind(locs, s$points[[1]])
# }
for (i in seq(1, length(states), length.out = 10000)) {
  s <- states[[i]] 
  locs <- rbind(locs, s$points[[1]])
}

locs

library(GGally)

ggpairs(locs)

plot(locs$x, col="red", main="Trace plot for x of a particular point")
lines(rep(states[[order(ls, decreasing = 1)[1]]]$points[[1]]$x, length(locs$x)))
plot(locs$y, col="green", main="Trace plot for y of a particular point")
lines(rep(states[[order(ls, decreasing = 1)[1]]]$points[[1]]$y, length(locs$y)))
plot(locs$w, col="blue", main="Trace plot for w of a particular point")
lines(rep(states[[order(ls, decreasing = 1)[1]]]$points[[1]]$w, length(locs$w)))
plot(locs$h, col="purple", main="Trace plot for h of a particular point")
lines(rep(states[[order(ls, decreasing = 1)[1]]]$points[[1]]$h, length(locs$h)))
plot(ks, col="purple", main="Trace plot for k")
```
```{r}
# folder <- sample(folders, 1)
# folder_frame_files <- list()
set.seed(2020)

library(jpeg)
library(xml2)
folder_frame_files <- lapply(folders, function(f) { Sys.glob(paste(f, "/**.jpg", sep="")) })
folder_xmls <- lapply(folders, function(f) { xml_find_all(read_xml(Sys.glob(paste(f, "/**.xml", sep=""))), "frame//objectlist") })
folder_ks <- lapply(folder_xmls, function(f) {
  lapply(f, function(x) { length(xml_find_all(x, "object/box")) })
})
```

```{r}
library(rlist)

sample_state <- function() {
  # TODO sample poisson
  k_gen <- sample(1:10, 1)
  points_gen <- list()
  
  for (k in 1:k_gen) {
    xc <- runif(1, 0, w)
    yc <- runif(1, 0, h)
  
    ww <- clamp(rnorm(1, mean = w_model(yc), sd = w_sd), min_w, w)
    hh <- clamp(rnorm(1, mean = h_model(yc), sd = h_sd), min_h, h)
    
    points_gen[[k]] <- list(x=xc,y=yc,w=ww,h=hh)
    
    points_gen[[k]]$x <- clamp(xc, ww/2+1+min_w/2, w-ww/2-min_w/2)
    points_gen[[k]]$y <- clamp(yc, hh/2+1+min_h/2, h-hh/2-min_h/2)
  }
  
  return (list(
    k = k_gen,
    points = points_gen
  ))
}

x_sd <- w*.2
y_sd <- h*.2

run_rjmcmc <- function(foreground, N=3000) {
  posterior <- function (state) {
    state_mask <- array(0, dim=c(h, w))
  
    overlap <- 0
    for (i in 1:state$k) {
      point <- state$points[[i]]
      for (x in round(point$x - point$w/2):round(point$x + point$w/2)) {
        for (y in round(point$y - point$h/2):round(point$y + point$h/2)) {
          # if (x < 1 || x > w || y < 1 || y > h) {
          #   print(c(x, y, point$w, point$h))
          #   print(point)
          #   print(state)
          #   next;
          # }
          if (state_mask[y, x] == 0) {
            state_mask[y, x] = 1
          } else {
            overlap <- overlap + 1
          }
        }
      }
    }
    N10 <- sum(state_mask == 1 & foreground == 0)
    N01 <- sum(state_mask == 0 & foreground == 1)
  
    measures <- c(N10, N01, overlap)
  
    weights <- c(0.005, 0.1, 0.01)
    
    Z <- min(measures %*% weights, 600)
  
    return (exp(-Z) * prior(state))
  }
  
  pi_ratio <- function(state_1, state_2) {
    state_1$posterior /  state_2$posterior
  }
  
  propose_update <- function(state) {
    i <- sample(1:state$k, 1)
    p <- state$points[[i]]
  
    p$x <- rnorm(1, mean = p$x, sd=x_sd)
    p$y <- rnorm(1, mean = p$y, sd=y_sd)
    
    p$w <- clamp(rnorm(1, mean = w_model(p$y), sd = w_sd), min_w, w)
    p$h <- clamp(rnorm(1, mean = h_model(p$y), sd = h_sd), min_h, h)
    
    p$x <- clamp(p$x, p$w/2+min_w/2, w-p$w/2-min_w/2)
    p$y <- clamp(p$y, p$h/2+1+min_h/2, h-p$h/2-min_h/2)
    
    state$points[[i]] <- p
      
    return (state)
  }
  
  propose_birth <- function(state) {
    state$k <- state$k + 1
    
    p <- list(
      x = runif(1, 0, w),
      y = runif(1, 0, h)
    )
    
    p$w <- clamp(rnorm(1, mean = w_model(p$y), sd = w_sd), min_w, w)
    p$h <- clamp(rnorm(1, mean = h_model(p$y), sd = h_sd), min_h, h)
    
    p$x <- clamp(p$x, p$w/2+min_w/2, w-p$w/2-min_w/2)
    p$y <- clamp(p$y, p$h/2+1+min_h/2, h-p$h/2-min_h/2)
    
    state$points[[state$k]] <- p
  
    return (state)
  }
  
  propose_death <- function(state) {
    i <- sample(1:state$k, 1)
    
    state$k <- state$k - 1
    
    state$points <- list.remove(state$points, i)
    
    state$removed <- i
  
    return (state)
  }
  
  points_dist <- function(a, b) {
    (a$x-b$x)^2 + (a$y-b$y)^2
  }
  
  propose_merge <- function(state) {
    dists <- array(Inf, dim=c(state$k, state$k))
    
    for (i in 1:(state$k - 1)) {
      for (j in (i + 1):state$k) {
        pi <- state$points[[i]]
        pj <- state$points[[j]]
        dists[i, j] <- points_dist(pi, pj)
      }
    }
    
    remove_i <- floor(which(dists == min(dists)) / state$k)
    
    state$k <- state$k - 1
    
    state$points <- list.remove(state$points, remove_i)
    
    state$removed <- remove_i
  
    return (state)
  }
  
  # TODO birth and death proposal probabilities according to poisson
  
  propose <- function(state) {
    
    process <- runif(1)
    
    new_state <- NULL
    
    if (process < 0.1) {
      new_state <- propose_birth(state)
    } else if (process < 0.175 && state$k > 1) {
      new_state <- propose_death(state)
    } else if (process < 0.20 && state$k > 1) {
      new_state <- propose_merge(state)
    } else {
      new_state <- propose_update(state)
    }
    
    new_state$posterior <- posterior(new_state)
    
    return (new_state)
  }
  
  prior <- function(x) {
    prob <- 1
    for (p in x$points) {
      prob <- prob * dnorm(p$w, mean = w_model(p$y), sd = w_sd) * dnorm(p$h, mean = h_model(p$y), sd = h_sd)
    }
    prob
  }
  
  proposal_update_prob <- function(x) {
    prior(x)
  }
  
  proposal_prob_ratio <- function(x, y) {
    k_diff <- y$k - x$k
    
    if (k_diff > 1) {
      # Expanded
      1 / prior(y$points[y$k])
    } else if (k_diff < 1) {
      # Contracted
      prior(x$points[y$removed]) / 1
    } else {
      # Updated
      proposal_update_prob(x) / proposal_update_prob(y)
    }
  }
  
  initial_state <- sample_state()
  
  initial_state$posterior <- posterior(initial_state)
  
  states <- metropolis_hastings(
    propose,
    proposal_prob_ratio,
    pi_ratio,
    N,
    initial_state
  )
}

```



```{r}
sample_solution <- function() {
  folder <- sample(1:length(folder_frame_files), 1)
  frame_nr <- sample(1:length(folder_frame_files[[folder]]), 1)
  frame_jpeg <- readJPEG(folder_frame_files[[folder]][[frame_nr]], native=FALSE)
  frame_k <- folder_ks[[folder]][[frame_nr]]
  
  foreground <- background_subtraction(frame_jpeg, background)
  
  # plot_image(from_grayscale(foreground))
  # plot_image(frame_jpeg)
  # plot_image(background)
  
  states <- run_rjmcmc(foreground, 3000)
  
  ls <- unlist(lapply(states, function(s) { s$posterior }))
  ks <- unlist(lapply(states, function(s) { s$k }))
  map_index <- order(ls, decreasing = 1)[1]
  
  est_k <- ks[map_index]
  
  getmode <- function(v) {
     uniqv <- unique(v)
     uniqv[which.max(tabulate(match(v, uniqv)))]
  }
  
  # render_state(states[[map_index]], foreground)
  
  return (list(
    folder=folder,
    frame_nr=frame_nr,
    frame_k=frame_k,
    est_k=est_k,
    mode_k=mode(ks)#,
    # best_state=states[[map_index]]
  ))
}

K <- 500

# sample_solution()

# solutions <- data.frame()
for (i in 1:K) {
  solutions <- rbind(solutions, sample_solution())
}

plot(solutions$frame_k)
points(solutions$est_k, col="red")
plot(solutions$frame_k, solutions$est_k)

summary(lm(frame_k ~ est_k, data = solutions))

sum(solutions$est_k == solutions$frame_k) / nrow(solutions)
sum(abs(solutions$est_k - solutions$frame_k) <= 1) / nrow(solutions)
sum(abs(solutions$est_k - mean(solutions$est_k)) <= 1) / nrow(solutions)
hist(solutions$est_k - solutions$frame_k)


# folder <- sample(1:length(folder_frame_files), 1)
# frame_nr <- sample(1:length(folder_frame_files[[folder]]), 1)
# frame_jpeg <- readJPEG(folder_frame_files[[folder]][[frame_nr]], native=FALSE)
# frame_k <- folder_ks[[folder]][[frame_nr]]
# 
# foreground <- background_subtraction(current_frame, background)
# 
# plot_image(from_grayscale(foreground))
# plot_image(current_frame)
# plot_image(background)
# 
# states <- run_rjmcmc(foreground, 5000)

# ls <- c()
# ps <- c()
# ks <- c()
# for (s in states) {
#   # ls <- c(ls, likelihood(s))
#   ls <- c(ls, s$posterior)
#   ps <- c(ps, prior(s))
#   ks <- c(ks, s$k)
# }
# # plot(ls, col="black", type="l", ylim=c(0,quantile(c(ls, ps), 0.8)))
# plot(ls, col="black", type="l", main="Posterior along MCMC runs")
# # lines(ps, col="red")
# plot(ks, type="l", main="Number of people along MCMC runs")
# hist(ks)
# 
# render_states <- function(states, indices, title) {
#   for (s in states[indices]) {
#     render_state(s, title)
#   }
# }
# 
# render_states(states, seq(1,4), "first")
# render_states(states, length(states)-seq(1,5)-1, "last")
# render_states(states, order(ls, decreasing = 1)[c(seq(1,20))], "best")
# render_states(states, order(ls, decreasing = 1)[c(length(states)-seq(1,5)-1)], "worst")
# render_states(states, sample(1:length(states), 20), "random")
```



